// <auto-generated />
using InfrastructureAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfrastructureAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260329193037_NombreMigracion")]
    partial class NombreMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DomainAPI.Entities.Campeones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ArmaduraBase")
                        .HasColumnType("float");

                    b.Property<double>("AtaqueBase")
                        .HasColumnType("float");

                    b.Property<int>("Dificultad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("VidaBase")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Campeones");
                });

            modelBuilder.Entity("DomainAPI.Entities.Campeones", b =>
                {
                    b.OwnsOne("DomainAPI.Entities.Rol", "RolPrincipal", b1 =>
                        {
                            b1.Property<int>("CampeonesId")
                                .HasColumnType("int");

                            b1.HasKey("CampeonesId");

                            b1.ToTable("Campeones");

                            b1.WithOwner()
                                .HasForeignKey("CampeonesId");
                        });

                    b.Navigation("RolPrincipal");
                });
#pragma warning restore 612, 618
        }
    }
}
